version: "3.9"
services:
  neosvr-headless:
    build:
      context: https://github.com/hazre/neosvr-headless.git
      args:
       - HOSTUSERID=${HOSTUSERID:-1000}
       - HOSTGROUPID=${HOSTGROUPID:-1000}
    tty: true
    stdin_open: true
    environment:
      - STEAMBETA=${STEAMBETA}
      - STEAMBETAPASSWORD=${STEAMBETAPASSWORD}
      - STEAMLOGIN=${STEAMLOGIN}
      - CLEANASSETS=${CLEANASSETS:-true}
      - CLEANLOGS=${CLEANLOGS:-true}
    volumes:
      - "./Config:/Config"
      - "./Logs:/Logs"
      - "/etc/localtime:/etc/localtime:ro"
      # optional unless you enable mods
      # - "./nml_libs:/nml_libs"
      # - "./nml_mods:/nml_mods"
    restart: unless-stopped
